Merged PR 7172: add apprunner for L! docker
add apprunner

diff --git a/dockers/registry-jobs/custom/barrier_horovod/horovod0.15.2barrier-pytorch1.0.0-tf1.12-py2.6-py3.6-openmpi/toolkit-execute b/dockers/registry-jobs/custom/barrier_horovod/horovod0.15.2barrier-pytorch1.0.0-tf1.12-py2.6-py3.6-openmpi/toolkit-execute
--- a/dockers/registry-jobs/custom/barrier_horovod/horovod0.15.2barrier-pytorch1.0.0-tf1.12-py2.6-py3.6-openmpi/toolkit-execute
+++ b/dockers/registry-jobs/custom/barrier_horovod/horovod0.15.2barrier-pytorch1.0.0-tf1.12-py2.6-py3.6-openmpi/toolkit-execute
@@ -1,67 +1,53 @@
 #!/bin/bash
 
-# Default values
-CONFIG_FILE=NONE
-DATA_DIR=NONE
-LOG_DIR=NONE
-MODEL_DIR=NONE
-PREV_MODEL_PATH=NONE
-IS_MEMCHECK=FALSE
+# Workaround: Philly will change /etc/hosts before launching toolkit-execute, 127.0.0.1=>localhost is somehow removed
+# Without 127.0.0.1=>localhost, tf 0.12 distributed training will hang
+if [ "$OMPI_COMM_WORLD_LOCAL_RANK" == "0" ]; then
+    # Update /etc/hosts only once per container
+    echo "add localhost to /etc/hosts"
+    sudo chmod 777 /etc/hosts
+    printf "127.0.0.1\tlocalhost\n" >> /etc/hosts
+    cat /etc/hosts
+fi
 
-# extra argument
-EXTRA_ARGS=""
 
-# parse the argument
-while [[ $# > 0 ]]
-do
-key="$1"
+# Workaround: currently Philly does not handle quote in extraParams well, quote always get dropped before final script is called
+# Use --app-args-begin and --app-args-end as a workaround, anything between --app-args-begin and --app-args-end will be combined as --app-args and pass down
+args=("$@")
+new_args=()
 
-case $key in
-    -h|--help)
-    echo "Usage: runCust [run_options]"
-    echo "Options:"
-    echo "  -c|--configFile <config> - which configuration file to use (default NONE)"
-    echo "  -d|--dataDir <path> - directory path to input files (default NONE)"
-    echo "  -l|--logDir <path> - directory path to save the log files (default NONE)"
-    echo "  -m|--modelDir <path> - directory path to save the model files (default NONE)"
-    echo "  --memCheck - start job in memcheck mode (default FALSE)"
-    exit 1
-    ;;
-    -c|--configFile)
-    CONFIG_FILE="$2"
-    shift # pass argument
-    ;;
-    -d|--dataDir)
-    DATA_DIR="$2"
-    shift # pass argument
-    ;;
-    -l|--logDir)
-    LOG_DIR="$2"
-    shift # pass argument
-    ;;
-    -m|--modelDir)
-    MODEL_DIR="$2"
-    shift # pass argument
-    ;;
-    --memCheck)
-    IS_MEMCHECK=TRUE
-    ;;
-    *)
-    EXTRA_ARGS="$EXTRA_ARGS $1"
-    ;;
-esac
-shift # past argument or value
+in_app_args=0
+app_args=""
+
+for arg in "${args[@]}"; do
+    if [ "${arg}" == "--app-args-begin" ]; then
+        in_app_args=1
+        continue
+    fi
+
+    if [ "${arg}" == "--app-args-end" ]; then
+        in_app_args=0
+        new_args+=("--app-args")
+        new_args+=("$app_args")
+        continue
+    fi
+
+    if [ ${in_app_args} -eq 0 ]; then
+        new_args+=("$arg")
+    else
+        app_args+="$arg "
+    fi
 done
 
-echo "toolkit-execute: CONFIG_FILE=$CONFIG_FILE"
-echo "toolkit-execute: DATA_DIR=$DATA_DIR"
-echo "toolkit-execute: LOG_DIR=$LOG_DIR"
-echo "toolkit-execute: MODEL_DIR=$MODEL_DIR"
-echo "toolkit-execute: IS_MEMCHECK=$IS_MEMCHECK"
-echo "toolkit-execute: EXTRA_ARGS=$EXTRA_ARGS"
+export CLASSPATH="$(/usr/local/hadoop/bin/hadoop classpath --glob)"
+export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
+export HADOOP_HOME=/usr/local/hadoop
+export HADOOP_HDFS_HOME=/usr/local/hadoop
 
-cd $CODE_DIR
+apprunner_dir="/tmp/apprunner"
+cd $apprunner_dir
 
-# do some thing, for now is
-echo "will execute:$EXTRA_ARGS"
-sleep infinity
+# Workaround: pip install might fail due to permission issue even we already set chmod to 777
+sudo chown $USER:$USER -R $apprunner_dir
+
+python3 ./.working/apprunner/apprunner.py launch --host-platform Philly "${new_args[@]}" || exit $?
